[package]
name = "planchon_darboux"
version = "0.1.0"
edition = "2021"
readme = "readme.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
ndarray-npy = "0.8.1"
ndarray-stats = "0.5.1"